Repository oschwengers/bakta, pull requests merged in 2021-05, with the labels that each got.

#51 Update README to include latest zenodo link
  README.md
Labels: documentation, enhancement

#50 Fix typo in genbank flat file format output
  bakta/io/insdc.py
Labels: bug

#52 Catch amrfinderplus db issue #49
  bakta/db.py
  bakta/utils.py
Labels: enhancement
