Repository oschwengers/bakta, pull requests merged in 2023-08, with the labels that each got.

#227 Replace setup-miniconda by setup-micromamba GH action
  .github/workflows/ci.yml
Labels: bug

#219 Replace hmmer with py hmmer
  README.md
  bakta/features/cds.py
  bakta/features/orf.py
  bakta/main.py
  environment.yml
  setup.py
Labels: enhancement

#230 Fix and expand CWL wrapper
  bakta.cwl
Labels: bug, enhancement

#231 Fix PyPI CD
  .github/workflows/cd-pypi.yml
Labels: bug
